package org.ohmyloader.testmod

import org.ohmyloader.api.network.OMLNetwork
import org.ohmyloader.api.network.OMLNetworkRegistry
import org.ohmyloader.api.network.OMLPacketBuffer
import org.ohmyloader.api.network.OMLPayloadCodec
import org.ohmyloader.api.network.OMLPayloadType
import kotlin.random.Random

/**
 * Custom-payload round trip (M3 / T-3.3). Singleplayer runs the client and the server as two ends of a
 * real loopback connection, so one send covers channel registration, the game's identifier routing,
 * both codecs and both inbound hooks.
 *
 * The pairing token is generated by the sender and travels inside the payload: the receiving side echoes
 * it back without interpreting it, and the sender judges the match. Comparing a locally generated value
 * on both sides would pass in singleplayer and lie about a real two-process connection.
 */
object NetworkProbe {

    private const val LABEL = "oml-e2e-network"

    private data class Ping(val nonce: Int, val label: String)

    private data class Pong(val nonce: Int, val label: String)

    private object PingCodec : OMLPayloadCodec<Ping> {
        override fun write(buffer: OMLPacketBuffer, value: Ping) {
            buffer.writeInt(value.nonce)
            buffer.writeString(value.label)
        }

        override fun read(buffer: OMLPacketBuffer): Ping = Ping(buffer.readInt(), buffer.readString())
    }

    private object PongCodec : OMLPayloadCodec<Pong> {
        override fun write(buffer: OMLPacketBuffer, value: Pong) {
            buffer.writeInt(value.nonce)
            buffer.writeString(value.label)
        }

        override fun read(buffer: OMLPacketBuffer): Pong = Pong(buffer.readInt(), buffer.readString())
    }

    private val PING = OMLPayloadType("probe_ping", PingCodec)
    private val PONG = OMLPayloadType("probe_pong", PongCodec)

    private val nonce = Random.nextInt(1, 1_000_000)

    @Volatile
    private var echoed = false

    @Volatile
    private var inWorld = false

    @Volatile
    private var sendAttempts = 0

    @Volatile
    private var serverProbed = false

    /** Declared from the mod entry point; both directions exist so both sides' hooks are exercised. */
    fun declareNetwork(network: OMLNetworkRegistry) {
        network.clientToServer(PING) { value, context ->
            E2E.check("network.server_received", value.label == LABEL && value.nonce > 0, "decoded ${value.nonce}/${value.label}")
            val sender = context.senderName
            if (sender == null) {
                E2E.check("network.round_trip", false, "the server saw no player name on this connection")
            } else {
                OMLNetwork.sendToPlayer(PONG, Pong(value.nonce, value.label), sender)
            }
        }
        network.serverToClient(PONG) { value, _ ->
            echoed = true
            E2E.check("network.round_trip", value.nonce == nonce && value.label == LABEL, "echoed ${value.nonce}/${value.label}, sent $nonce/$LABEL")
        }
    }

    /** Client side. A run that never joins a world has no connection to send on, so it sends nothing. */
    fun worldLoaded() {
        inWorld = true
    }

    /** Retries until the connection accepts the send; a window that closes without one is the failure. */
    fun tickClientSide() {
        if (echoed || !inWorld) return
        val outcome = runCatching { OMLNetwork.sendToServer(PING, Ping(nonce, LABEL)) }
        if (outcome.isSuccess) return
        sendAttempts++
        if (sendAttempts >= 200) {
            E2E.check("network.round_trip", false, "no client-to-server path after 200 ticks: ${outcome.exceptionOrNull()}")
        }
    }

    /** Server side. A name that matches nobody is a warning, not an exception — the check asserts that. */
    fun tickServerSide() {
        if (serverProbed) return
        serverProbed = true
        val outcome = runCatching { OMLNetwork.sendToPlayer(PONG, Pong(1, LABEL), "oml_e2e_absent_player") }
        E2E.check("network.unknown_player", outcome.isSuccess, "sending to an absent player threw ${outcome.exceptionOrNull()}")
    }
}
